name: Build Docker Images

on:
  push:
    branches: master
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[build skip]')"
    outputs:
      strategy: ${{ steps.generate-jobs.outputs.strategy }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: '12.x'

    - id: generate-jobs
      name: Generate Jobs
      run: |
        npm install
        strategy="$(node build.js generateJobs)"
        echo "::set-output name=strategy::$strategy"

  build:
    needs: generate-jobs
    strategy: ${{ fromJson(needs.generate-jobs.outputs.strategy) }}
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '12.x'

      - name: Login into Docker Registery
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "shyim" --password-stdin

      - name: Login into Github Docker Registery
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u shyim --password-stdin

      - name: Build ${{ matrix.name }}
        run: ${{ matrix.runs.build }}
